// Code generated by ormc; DO NOT EDIT.
// NOTE: Schema() and Values() must always be in the same field order.
// String PK: set via github.com/tinywasm/unixid before calling db.Create().
package agentswitch

import (
	"github.com/tinywasm/orm"
)

func (m *AgentSwitch) Schema() []orm.Field {
	return []orm.Field{
		{Name: "id", Type: orm.TypeText, Constraints: orm.ConstraintPK},
		{Name: "is_enabled", Type: orm.TypeBool, Constraints: orm.ConstraintNotNull},
		{Name: "changed_by", Type: orm.TypeText, Constraints: orm.ConstraintNotNull},
		{Name: "reason", Type: orm.TypeText, Constraints: orm.ConstraintNone},
	}
}

func (m *AgentSwitch) Values() []any {
	return []any{
		m.ID,
		m.IsEnabled,
		m.ChangedBy,
		m.Reason,
	}
}

func (m *AgentSwitch) Pointers() []any {
	return []any{
		&m.ID,
		&m.IsEnabled,
		&m.ChangedBy,
		&m.Reason,
	}
}

var AgentSwitchMeta = struct {
	TableName string
	ID string
	IsEnabled string
	ChangedBy string
	Reason string
}{
	TableName: "agent_switch",
	ID: "id",
	IsEnabled: "is_enabled",
	ChangedBy: "changed_by",
	Reason: "reason",
}

func ReadOneAgentSwitch(qb *orm.QB, model *AgentSwitch) (*AgentSwitch, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllAgentSwitch(qb *orm.QB) ([]*AgentSwitch, error) {
	var results []*AgentSwitch
	err := qb.ReadAll(
		func() orm.Model { return &AgentSwitch{} },
		func(m orm.Model) { results = append(results, m.(*AgentSwitch)) },
	)
	return results, err
}
