// DO NOT EDIT. generated by github.com/tinywasm/orm

package agentswitch

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

func (m *AgentSwitch) FormName() string {
	return "agent_switch"
}

var _schemaAgentSwitch = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, PK: true},
		{Name: "is_enabled", Type: fmt.FieldBool, NotNull: true},
		{Name: "changed_by", Type: fmt.FieldText, NotNull: true},
		{Name: "reason", Type: fmt.FieldText},
	}

func (m *AgentSwitch) Schema() []fmt.Field { return _schemaAgentSwitch }

func (m *AgentSwitch) Pointers() []any {
	return []any{
		&m.ID,
		&m.IsEnabled,
		&m.ChangedBy,
		&m.Reason,
	}
}

var AgentSwitch_ = struct {
	TableName string
	ID string
	IsEnabled string
	ChangedBy string
	Reason string
}{
	TableName: "agent_switch",
	ID: "id",
	IsEnabled: "is_enabled",
	ChangedBy: "changed_by",
	Reason: "reason",
}

func ReadOneAgentSwitch(qb *orm.QB, model *AgentSwitch) (*AgentSwitch, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllAgentSwitch(qb *orm.QB) ([]*AgentSwitch, error) {
	var results []*AgentSwitch
	err := qb.ReadAll(
		func() orm.Model { return &AgentSwitch{} },
		func(m orm.Model) { results = append(results, m.(*AgentSwitch)) },
	)
	return results, err
}
